import { WorkflowConfig } from './types';

export const loanApprovalWorkflow: WorkflowConfig = {
  id: 'loan-approval-v1',
  name: 'Loan Approval Workflow',
  description: 'Processes loan applications through identity verification, credit assessment, and income-to-debt ratio analysis.',
  version: 1,
  schema: {
    applicantName: { type: 'string', required: true, label: 'Applicant Name' },
    email: { type: 'string', required: true, label: 'Email Address' },
    age: { type: 'number', required: true, label: 'Age' },
    annualIncome: { type: 'number', required: true, label: 'Annual Income ($)' },
    loanAmount: { type: 'number', required: true, label: 'Loan Amount ($)' },
    employmentStatus: { type: 'string', required: true, label: 'Employment Status' },
    existingDebt: { type: 'number', required: true, label: 'Existing Debt ($)' },
  },
  rules: [
    {
      id: 'r1-age-min',
      name: 'Minimum Age Check',
      description: 'Applicant must be at least 18 years old',
      type: 'mandatory',
      field: 'age',
      operator: '>=',
      value: 18,
      onFail: 'reject',
      priority: 1,
    },
    {
      id: 'r2-name-exists',
      name: 'Name Required',
      description: 'Applicant name must be provided',
      type: 'mandatory',
      field: 'applicantName',
      operator: 'exists',
      value: true,
      onFail: 'reject',
      priority: 1,
    },
    {
      id: 'r3-email-valid',
      name: 'Email Format',
      description: 'Email must be valid format',
      type: 'mandatory',
      field: 'email',
      operator: 'regex',
      value: '^[^@]+@[^@]+\\.[^@]+$',
      onFail: 'reject',
      priority: 1,
    },
    {
      id: 'r4-credit-score',
      name: 'Credit Score Threshold',
      description: 'Credit score must be at least 600',
      type: 'threshold',
      field: 'creditScore',
      operator: '>=',
      value: 600,
      onFail: 'reject',
      priority: 2,
    },
    {
      id: 'r5-credit-good',
      name: 'Good Credit Score',
      description: 'Credit score above 700 for auto-approval track',
      type: 'threshold',
      field: 'creditScore',
      operator: '>=',
      value: 700,
      onFail: 'manual_review',
      priority: 2,
    },
    {
      id: 'r6-income-min',
      name: 'Minimum Income',
      description: 'Annual income must be at least $20,000',
      type: 'threshold',
      field: 'annualIncome',
      operator: '>=',
      value: 20000,
      onFail: 'reject',
      priority: 3,
    },
    {
      id: 'r7-dti-ratio',
      name: 'Debt-to-Income Ratio',
      description: 'Loan + existing debt must not exceed 40% of annual income',
      type: 'conditional',
      field: 'annualIncome',
      operator: '>=',
      value: 0, // This is a composite check handled specially
      onFail: 'manual_review',
      priority: 3,
    },
    {
      id: 'r8-employment',
      name: 'Employment Verification',
      description: 'Must be employed or self-employed',
      type: 'mandatory',
      field: 'employmentStatus',
      operator: 'in',
      value: ['employed', 'self-employed'],
      onFail: 'manual_review',
      priority: 2,
    },
  ],
  stages: [
    {
      id: 'stage-1-identity',
      name: 'Identity & Eligibility',
      rules: ['r1-age-min', 'r2-name-exists', 'r3-email-valid'],
      onAllPass: 'stage-2-credit',
      onAnyFail: 'reject',
      retryable: false,
      maxRetries: 0,
    },
    {
      id: 'stage-2-credit',
      name: 'Credit Assessment',
      rules: ['r4-credit-score', 'r5-credit-good'],
      onAllPass: 'stage-3-financial',
      onAnyFail: 'manual_review',
      retryable: true,
      maxRetries: 2,
    },
    {
      id: 'stage-3-financial',
      name: 'Financial Analysis',
      rules: ['r6-income-min', 'r8-employment'],
      onAllPass: 'approve',
      onAnyFail: 'manual_review',
      retryable: false,
      maxRetries: 0,
    },
  ],
};
